title: Passpartout
email: ok.protsukha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Travel Blog to document our trip across the world 
  and all the encounters that come along.
permalink: ':title/'
baseurl: "/passpartout" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Passpartout # add your name
author-pic: OksanaNico_About.jpg
about-author: Oksana and Nico - we are a couple and tech workers who embarked on a travel adventure to learn more about the world around us and bring the knowledge into our lives back home.

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: oksanaprotsukha # Add your Github handle
twitter: '@passpartout' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-responsive-image

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
